### ISSUE TITLE
Box::{into_raw, from_raw} are no longer unstable in 1.4.0

### ISSUE THREAD

**Issue by huonw** [shepmaster/rust-ffi-omnibus#24]
In Objects:

> A pair of unstable functions, Box::into_raw and Box::from_raw, exist that promise to make this process a bit more ergonomic in the future.

The ergonomicity is now!

- https://doc.rust-lang.org/std/boxed/struct.Box.html#method.into_raw
- https://doc.rust-lang.org/std/boxed/struct.Box.html#method.from_raw

**Comment by shepmaster** [comment]
Closed via #25
