### ISSUE TITLE
Node Example leak

### ISSUE THREAD

**Issue by kjvalencik** [shepmaster/rust-ffi-omnibus#28]
https://github.com/shepmaster/rust-ffi-omnibus/blob/master/examples/objects/src/main.js

This example appears to leak a ton of memory. But, I'm not sure why. If I call this in a loop 1000 times, Node.js allocates and never frees 3 GB of memory. This is memory in C++ land and not on the JS heap (a JS heapdump is virtually empty).

This remains true even if I call it in a function and then outside of that function force a GC.

What is odd, Rust appears to be freeing memory properly. If I add a println to free it gets called and if I use an explicit `libc::free` I get a double free error.

In addition, I get this *exact* same issue if I manually write the C++ bindings rather than using `node-ffi`.

Do you have any thoughts on why this might be? I am using Node `v4.2.4` and Rust `1.5.0`.

```text
==17353== LEAK SUMMARY:
==17353==    definitely lost: 1,296 bytes in 41 blocks
==17353==    indirectly lost: 5,792,343 bytes in 99,995 blocks
==17353==      possibly lost: 1,138 bytes in 4 blocks
==17353==    still reachable: 6,889 bytes in 68 blocks
==17353==         suppressed: 0 bytes in 0 blocks
==17353== Reachable blocks (those to which a pointer was found) are not shown.
==17353== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==17353== 
==17353== For counts of detected and suppressed errors, rerun with: -v
==17353== ERROR SUMMARY: 40 errors from 40 contexts (suppressed: 0 from 0)
```

**Comment by kjvalencik** [comment]
One possible cause is the way `node-ffi` uses a `Buffer` to wrap a pointer and pass it back to JS. My C++ bindings are doing the same thing. I am currently investigating using a `v8::External` instead.

**Comment by shepmaster** [comment]
I assume you've just modified the example code to add a loop around it? Something like this:

```js
for (i = 0; i < 1000; i++) {
  try {
    var database = new ZipCodeDatabase();
    database.populate();
    var pop1 = database.populationOf('90210');
    var pop2 = database.populationOf('20500');
    console.log(pop1 - pop2);
  } finally {
    database.free();
  }
}
```

When I run that with Node v5.3.0, a development version of Rust, and these dependencies:

```
    "ffi": "^2.0.0",
    "jscs": "^2.8.0",
    "jshint": "^2.8.0",
    "ref": "^1.3.0",
    "ref-array": "^1.1.1",
    "ref-struct": "^1.0.1"
```

I do not see a marked memory growth through high-level tools. I'm running in valgrind now.

**Comment by kjvalencik** [comment]
The switch to `v8::External` resulted in the same leak. I am doing:

```js
Array.from(new Int8Array(7e6)).map(/* ... */)
```

I'll try a vanilla loop to see if it makes a difference.

**Comment by shepmaster** [comment]
> I'm running in valgrind now.

```
==23821== LEAK SUMMARY:
==23821==    definitely lost: 3,956 bytes in 64 blocks
==23821==    indirectly lost: 79,575 bytes in 25 blocks
==23821==      possibly lost: 3,006 bytes in 64 blocks
==23821==    still reachable: 17,206 bytes in 198 blocks
==23821==         suppressed: 58,844 bytes in 170 blocks
```

So it seems to be something outside of that.

**Comment by shepmaster** [comment]
@kjvalencik am I reading correctly - the `testZipNoLeak` method contains the body of the `testZipLeaks` method and it still doesn't leak? Like, somehow the `for` loop negates the leak?

**Comment by kjvalencik** [comment]
Sorry, I botched my copy and paste while cleaning up. I updated it to be what I'm actually running. I'm testing only one method at a time (the other commented out).

FWIW, the `map` doesn't appear to be the cause. If I do the same thing just allocating an array and looping over it, the leak still exists.

Summary:

If I only create 1 instance at a time, immediately freeing it, 1000 times, it only uses 15 MB of memory.
If I create 1000 instances and then free those 1000 instances (so, they exist at the same time), it uses 6 GB.

**Comment by shepmaster** [comment]
> If I only create 1 instance at a time, immediately freeing it, 1000 times, it only uses 15 MB of memory.
> If I create 1000 instances and then free those 1000 instances (so, they exist at the same time), it uses 6 GB.

That sounds very reasonable then. 1000 elephants in a room at the same time will need a bigger room than 1000 elephants in a room, one-at-a-time. :elephant: 

The next thing would be to figure out why valgrind would report the memory as leaked. The only thing that comes to mind is if you dropped your collection of pointers without calling the appropriate FFI `free` method. Your last posted code doesn't seem to exhibit any growth in memory lost when moving from `10` to `50` iterations. Do you still see the memory leak?

**Comment by kjvalencik** [comment]
Yes, I would definitely expect to see larger *transient* memory, but at the end of the program after forcing a GC, I would expect it to go back down to something reasonably small. With:

```js
global.gc();
setTimeout(() => {}, 10000);
```

At the end, I see the process still hovering around 3 GB and never getting any smaller. Since FFI wraps pointers in a Buffer, could this be the internal buffer pool growing large?

The free method is being called. In addition, I added a bit of logging and it's being called with different pointers (as expected):

```rust
#[no_mangle]
pub extern fn zip_code_database_free(ptr: *mut ZipCodeDatabase) {
    unsafe {
    	println!("{}", ptr as usize);
    	Box::from_raw(ptr);
    }
}
```

**Comment by shepmaster** [comment]
> At the end, I see the process still hovering around 3 GB and never getting any smaller

Interesting, as I *do* see the memory usage shrink back down to ~24 MB after the `gc`. In fact, I can take the `gc` call out and still see the drop in memory. Perhaps you could try a different version of Node or the `ffi` package? That's the only dependency being pulled in for this code I have locally. 

> `println!("{}", ptr as usize)`

FYI, you usually print a pointer with `{:p}`: `println!("{:p}", ptr);`

**Comment by kjvalencik** [comment]
I'll try Node 5 (already using latest FFI) and see if anything is different. Also, thanks for the tip on printing, I'm *very* new at Rust.

**Comment by kjvalencik** [comment]
Same results with Node 5.3. What's interesting, is no matter what I do, valgrind is giving me the exact same result. This leads me to believe that Node.js is properly cleaning up the memory on exit.

I'm not sure why it doesn't get cleaned up sooner though. Thanks again for your help.

**Comment by shepmaster** [comment]
I'm going to close this as there hasn't been any activity in a while. Feel free to reopen if we ever get more consistent reproduction steps.
