### ISSUE TITLE
Change crate type to cdylib

### ISSUE THREAD

**Issue by baby-bell** [shepmaster/rust-ffi-omnibus#40]
Cdylib was added to Cargo in 1.11, and since it strips the rust metadata, is the preferred way of doing FFI.

**Comment by ustulation** [comment]
@baby-bell :+1: Yes - it caused a ~25% reduction in size of `.so` in my project. Do you know if there is any reason why/when we should use `dylib` or is that going to be deprecated ?

**Comment by shepmaster** [comment]
Yes, this is something I was hoping to get around to, thank you for the reminder!

More than just switching it, I'd like to add a section containing the *why* and the differences (touching on some of what @ustulation is asking).

**Comment by baby-bell** [comment]
@ustulation I don't think `dylib` is going to be deprecated any time soon, but its use case is limited (it's really only useful for internal Rust stuff). For almost all purposes, `cdylib` is the way to go, especially since it [allows LTO](https://github.com/rust-lang/rust/pull/33553) among other nice things.

**Comment by shepmaster** [comment]
Indeed, there was [one tricky aspect to cdylibs](https://github.com/shepmaster/rust-ffi-omnibus/pull/46/commits/617a6a48d3aeb7fd195b5347173c8147c59df880).
