### ISSUE TITLE
Add Rust examples?

### ISSUE THREAD

**Issue by ctzurcanu** [shepmaster/rust-ffi-omnibus#85]
I could see usecases that call for executing functions compiled by rust into a dylib from another Rust program or library. Could not see anywhere on the web such an example (if even possible).

**Comment by Enet4** [comment]
This is possible by simply treating the dynamic library as a native C library. The process is described in the book on [Chapter 19](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code). See also the [Cargo guide](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) on how to tell the compile to link native libraries.

**Comment by ctzurcanu** [comment]
An example treated here probably would not hurt either. But... great. Thank you!
