### ISSUE TITLE
C# examples with SafeHandle should correctly implement IsInvalid

### ISSUE THREAD

**Issue by timfish** [shepmaster/rust-ffi-omnibus#89]
Currently, the examples use this wrapper for `SafeHandle`:
```c#
internal class ZipCodeDatabaseHandle : SafeHandle
{
    public ZipCodeDatabaseHandle() : base(IntPtr.Zero, true) {}

    public override bool IsInvalid
    {
        get { return false; }
    }

    protected override bool ReleaseHandle()
    {
        Native.zip_code_database_free(handle);
        return true;
    }
}
```
`IsInvalid` should probably be:
```c#
    public override bool IsInvalid
    {
        get { return handle == IntPtr.Zero; }
    }
```

**Comment by shepmaster** [comment]
I'd love a PR with this change!

**Ideally**, there'd be a way to tell if the handle is actually valid (points to the right type, etc.). I don't think there's much of a way to do that. Based on the [MSDN example](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle.isinvalid?view=netframework-4.8), I wonder if this is generally to be used when the native function returns an out-of-band error...

Any idea why there isn't a `Microsoft.Win32.SafeHandles.SafeHandleZeroIsInvalid`?
